ROIS: ["BuoyField","CoralSurvey","FindBreak","AcousticPinger","Shooter","Scan_The_Code","Gate_1","Gate_2","Gate_3","Dock", "DockEdgeLeft", "DockEdgeRight", "Exploring1", "Exploring2", "Exploring3", "Exploring4"]        
VOLUMES:
  #               low h, high h, low x, high x, low y, high y, low z, high z
  DOCK:           [1.0, 1.5, 8.0, 10.0, 8.0, 10.0, 2.75, 3.25]
  SHOOTER:        [0.75, 2.25, 3.0, 5.5, 3.0, 5.5, 2.5, 5.5]
  SCAN_THE_CODE:  [0.1, 0.75, 1.3, 2.25, 1.3, 2.25, 1.7, 2.5]
  TOTEM:          [-0.6, 0.0, 0.8, 1.8, 0.8, 1.8, 0.8, 1.8]
  BUOY:           [-1.25, -0.8, 0.125, 1.0, 0.125, 1.0, 0.125, 0.65]
MAP_SIZE_METERS: 2100.0
ROI_SIZE_METERS: 201.0
VOXEL_SIZE_METERS: 0.30
MIN_HITS_FOR_OCCUPANCY: 40  # Changed
MAX_HITS_IN_CELL: 200
LIDAR_HITS_INCREMENT: 35
MAXIMUM_Z_BELOW_LIDAR: 1.5 # Changed
MAXIMUM_Z_ABOVE_LIDAR: 1.25
MAX_ROLL_PITCH_ANGLE_DEG: 2.5
LIDAR_VIEW_ANGLE_DEG: 160
LIDAR_VIEW_DISTANCE_METERS: 60
LIDAR_VIEW_CONFIDENCE_DISTANCE_METERS: 40
LIDAR_MIN_VIEW_DISTANCE_METERS: 5.5
MIN_LIDAR_POINTS_FOR_OCCUPANCY: 10 # Changed
MIN_OBJECT_HEIGHT_METERS: 0.15
MIN_OBJECT_SEPERATION_DISTANCE: 3.0
MIN_GATE_SEPERATION: 20.0
MAX_GATE_SEPERATION: 50.0
MAX_GATE_ERROR_METRIC: 120.0
MIN_HITS_FOR_VOLUME: 31
OBJECT_INFLATION_PARAMETER: 2
VOXEL_SIZE_Z_METERS: 0.15
VOXEL_SIZE_Z_MIN_HITS: 10.0
