wamv_camera:
    - name: front_left_camera
      x: 0.75
      y: 0.1
      P: ${radians(15)}
    - name: front_right_camera
      x: 0.75
      y: -0.1
      P: ${radians(-30)}
    - name: middle_right_camera
      x: 0.75
      y: -0.3
      Y: ${radians(-90)}
      P: ${radians(15)}
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
      y: -0.2
lidar:
    - name: lidar_wamv
      type: 32_beam
      P: ${radians(8)}
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.54
      y: 0.30
      z: 1.30
      pitch: -0.80
      yaw: 0.10
wamv_pinger:
    - name: pinger
      position: '1 0 -1'
