image_width: 960
image_height: 600
camera_name: 00b09d0100e84a44
camera_matrix:
  rows: 3
  cols: 3
  data: [704.5182, 0, 476.1918, 0, 701.7624, 300.8320, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.1770, 0.1433, -.00031992, -0.0014, -0.0434]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.9991693896590961, -0.005453129023120229, 0.040383092404208, 0.005498346259638847, 0.9999843752085158, -0.001008725554093093, -0.04037696071621431, 0.001229927921290016, 0.9991837610372927]
projection_matrix:
  rows: 3
  cols: 4
  data: [704.5182, 0, 476.1918, 0, 0, 701.7624, 300.8320, 0, 0, 0, 1, 0]
