image_width: 1920
image_height: 1080
camera_name: seecam
camera_matrix:
  rows: 3
  cols: 3
  data: [1620.074305, 0.000000, 999.997358, 0.000000, 1608.670939, 551.660015, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.363743, 0.118477, -0.004066, -0.005029, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1381.206055, 0.000000, 999.313960, 0.000000, 0.000000, 1539.852295, 550.111827, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
