# This file has all of the thruster layout information needed by the sub
# This is used when simulating or running actual thrusters.
# CONFIDENT_MODE means that the thrusters on this port will never go offline (command packets
#   will always be sent even if no responses are received)

thruster_ports:
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if00-port0
    thruster_names: [FLH, FLV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if01-port0
    thruster_names: [FRH, FRV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if02-port0
    thruster_names: [BLH, BLV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if03-port0
    thruster_names: [BRH, BRV]
    CONFIDENT_MODE: False

# motor_id's should be globally unique among all thrusters
# position and orientation vectors should be specified in body frame
# calib contains the 4th to 1st order coefficients for a polynomial
#     mapping from thrust in Newtons to effort
thrusters:
  FLH: {
    motor_id:  0,
    position:  [0.2678, 0.2795, 0.0],
    direction: [0.866, -0.5, 0.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  FLV: {
    motor_id:  1,
    position:  [0.1583, 0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  FRH: {
    motor_id:  2,
    position:  [0.2678, -0.2795, 0.0],
    direction: [0.866, 0.5, 0.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  FRV: {
    motor_id:  3,
    position:  [0.1583, -0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  BLH: {
    motor_id:  4,
    position:  [-0.2678, 0.2795, 0.0],
    direction: [-0.866, -0.5, 0.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  BLV: {
    motor_id:  8,
    position:  [-0.1583, 0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  BRH: {
    motor_id:  6,
    position:  [-0.2678, -0.2795, 0.0],
    direction: [-0.866, 0.5, 0.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }
  BRV: {
    motor_id:  7,
    position:  [-0.1583, -0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-60.0, 90.0],
    calib:  {
        forward:  [0.0, 0.0, 0.0, 0.006623102],
        backward: [0.0, 0.0, 0.0, 0.006258566]
    }
  }

