# RISE terms:
alpha: 0, 0, 0, 0, 0, 0
beta: 0, 0, 0, 0, 0, 0
use_rise: false

# PD Terms -- X Y Z R P Y
# k -- used in calculating and smoothing error between current and desired
k: 5, 5, 2.5, 2, 0.7, 1.0
ks: 20, 20, 400, 50, 50, 40
# I terms
vel_feedforward: 0, 0, 2, 0.2, 0.5, 0.3
accel_feedforward: 3, 3, 2, 1, 0.5, 0.5

two_d_mode: false
