yolo_model:

  config_file:
    name: yolov4-tiny.cfg
  weight_file:
    name: yolov4-tiny.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - Badge
      - Bootlegger
      - Gun
      - Gunman
      - StartGate
