!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  frame: enu
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      frame: enu
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x1: -25
      x2: 150
      x3: 150
      x4: -50
      y1: 2
      y2: 3
      y3: 150
      y4: 150
      z1: 0
      z2: 0
      z3: 0
      z4: 0
    state: []
  x1: -25
  x2: 150
  x3: 150
  x4: -50
  y1: 2
  y2: 3
  y3: 150
  y4: 150
  z1: 0
  z2: 0
  z3: 0
  z4: 0
state: []
