---
!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  frame: enu
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      frame: enu
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x1: -20.0
      x2: 150.0
      x3: 150.0
      x4: -50.0
      y1: -5.0
      y2: 3.0
      y3: 150.0
      y4: 150.0
      z1: 0.0
      z2: 0.0
      z3: 0.0
      z4: 0.0
    state: []
  x1: -20.0
  x2: 150.0
  x3: 150.0
  x4: -50.0
  y1: -5.0
  y2: 3.0
  y3: 150.0
  y4: 150.0
  z1: 0.0
  z2: 0.0
  z3: 0.0
  z4: 0.0
state: []
