# Point cloud builder
---
accumulator_number_persistant_clouds: 15

# Filter
persistant_cloud_filter_min_neighbors: 20
persistant_cloud_filter_radius: 0.25

# Clusterer
cluster_tolerance_m: 4.4
cluster_min_points: 20
cluster_max_points: 1000

# Associator
associator_max_distance: 5
associator_forget_unseen: false

# Ogrid
ogrid_height_meters: 500
ogrid_width_meters: 500
ogrid_resolution_meters_per_cell: 0.3
ogrid_inflation_meters: 0.8

# Intensity filter
intensity_filter_min_intensity: 10
intensity_filter_max_intensity: 100

# yamllint disable-line rule:line-length
classifications: ["white_cylinder", "black_cylinder", "red_cylinder", "green_cylinder", "blue_manatee_buoy", "green_iguana_buoy", "red_python_buoy", "UNKNOWN"]
