image_width: 960
image_height: 600
camera_name: 00b09d0100f9afbc
camera_matrix:
  rows: 3
  cols: 3
  data: [718.589332, 0.000000, 482.086087, 0.000000, 715.846474, 298.525332, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.254767, 0.226677, -0.000554, 0.001963, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [670.373169, 0.000000, 483.685576, 0.000000, 0.000000, 685.802612, 297.679385, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
