image_width: 1920
image_height: 1080
camera_name: starboard_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [934.3227421846537, 0.0, 948.6819794905862, 0.0, 936.2811326182765, 508.9114181080822, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.23279532461454547, 0.04414111340686293, 0.0008110814392662328, -0.0029809693557722836, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [659.90771484375, 0.0, 921.924245586677, 0.0, 0.0, 855.1337280273438, 503.56472968469825, 0.0, 0.0, 0.0, 1.0, 0.0]
