color:
  buoy:
    red:
      LAB: [[0, 150, 135], [255, 205, 184]]

    green:
      LAB: [[0, 70, 130], [255, 120, 175]]

    yellow:
      LAB: [[0, 82, 145], [255, 148, 205]]

  channel_marker:
    hsv_low: [17.3988, 17.697, 223.125]
    hsv_high: [42.2619, 255.0, 255.0]
