# distance from any hydrophone to hydrophone 0
dist_h: 2.286e-02
# speed of sound in water
v_sound: 1482
#  target Frquency in Hz
triggering/target_frequency: 30000
#  tolerance around target frequerncy in Hz
triggering/frequency_tolerance: 100
# known min time between pings in sec
triggering/min_time_between_pings: 1.5
# threshold for triggering on gradient(max_convolution(bandpass(signal)))
triggering/threshold: 2.0
# how many seconds to offset the trigger time
triggering/trigger_offset: 0.0
triggering/enable_on_launch: True
