accel_feedforward: 0, 0, 0, 0, 0, 0
alpha: 50, 50, 50, 20, 20, 25
beta: 0, 0, 0, 0, 0, 10
k: 3,3,5,1.5,3,8
ks: 50, 50, 200, 20, 20, 30
two_d_mode: false
use_rise: false
vel_feedforward: 0, 0, 0, 0, 0, 0
